/* StitchOS module: interrupt stub frames + dispatcher (moos_ prefix)
 * Ported from: MOOS (C:\Users\fanqi\Desktop\自研操作系统\MOOS\NativeLib\interrupts_asm.asm,
 *              C:\Users\fanqi\Desktop\自研操作系统\MOOS\NativeLib\interrupts.cpp,
 *              C:\Users\fanqi\Desktop\自研操作系统\MOOS\Kernel\Misc\IDT.cs,
 *              C:\Users\fanqi\Desktop\自研操作系统\MOOS\Kernel\Misc\Interrupts.cs)
 * Original license: Unlicense (MOOS LICENSE = public-domain dedication; MIT also cited)
 * Changes: MASM pushaq/popaq rewritten as GAS macros in isr_stubs.S; the
 *          Windows x64 argument registers (rcx/rdx, kept for provenance) are
 *          mirrored into the SysV AMD64 argument registers (rdi/rsi) that
 *          clang actually reads; the MOOS "struct of delegate list" registry
 *          became a fixed 256-slot table with explicit overwrite semantics;
 *          the int 0x80 named-syscall lookup (IDT.cs) is dropped for phase-1.
 */
#ifndef STITCH_INTR_H
#define STITCH_INTR_H

#include <stitch/types.h>

/* Stack frame built by arch\x86_64\isr_stubs.S, lowest address first.
 *
 * Stub sequence (see isr_stubs.S):
 *   [CPU]  ss, rsp, rflags, cs, rip [, error_code]
 *   [stub] push $0            <- synthetic error code (only for vectors that
 *                                do NOT have a CPU-pushed one)
 *   [stub] push $vector
 *   [stub] push %rbp, %r15..%r8, %rdi, %rsi, %rbx, %rdx, %rcx, %rax
 *   -> %rsp points at moos_regs; %rdx/%rcx get the (frame, vector) pair as in
 *      the original MOOS Windows-x64 call, %rsi/%rdi carry them in SysV order.
 *
 * Reverse of the push order => struct field order below is exact memory
 * order; _Static_asserts lock the layout so asm and C cannot drift apart.
 */
struct moos_regs {
    uint64_t rax;          /* +0x00 */
    uint64_t rcx;          /* +0x08 */
    uint64_t rdx;          /* +0x10 */
    uint64_t rbx;          /* +0x18 */
    uint64_t rsi;          /* +0x20 */
    uint64_t rdi;          /* +0x28 */
    uint64_t r8;           /* +0x30 */
    uint64_t r9;           /* +0x38 */
    uint64_t r10;          /* +0x40 */
    uint64_t r11;          /* +0x48 */
    uint64_t r12;          /* +0x50 */
    uint64_t r13;          /* +0x58 */
    uint64_t r14;          /* +0x60 */
    uint64_t r15;          /* +0x68 */
    uint64_t rbp;          /* +0x70 (MOOS kept rbp outside RegistersStack) */
    uint64_t vector;       /* +0x78 pushed by the stub */
    uint64_t error_code;   /* +0x80 CPU-pushed or synthetic 0 */
    /* CPU-pushed iretq frame (MOOS InterruptReturnStack).
     * 64-bit rule: ss/rsp are pushed ONLY when the interrupt crosses a
     * privilege level. Kernel-only bring-up never crosses one, so those two
     * slots read stale stack memory until ring 3 exists - iretq itself pops
     * exactly as many slots as the CPU pushed, so the stub stays correct. */
    uint64_t rip;          /* +0x88 */
    uint64_t cs;           /* +0x90 */
    uint64_t rflags;       /* +0x98 */
    uint64_t rsp;          /* +0xA0 valid only after a ring transition */
    uint64_t ss;           /* +0xA8 valid only after a ring transition */
};

_Static_assert(sizeof(struct moos_regs) == 0xB0, "moos_regs must be 176 bytes");
_Static_assert(__builtin_offsetof(struct moos_regs, rax) == 0x00, "frame starts at rax");
_Static_assert(__builtin_offsetof(struct moos_regs, rbp) == 0x70, "rbp slot");
_Static_assert(__builtin_offsetof(struct moos_regs, vector) == 0x78, "vector slot");
_Static_assert(__builtin_offsetof(struct moos_regs, error_code) == 0x80, "error slot");
_Static_assert(__builtin_offsetof(struct moos_regs, rip) == 0x88, "iretq frame slot");

typedef void (*moos_irq_fn)(struct moos_regs *frame);

/* ---- provided by isr_stubs.S (generated by GAS .irp/.macro) ---- */
/* moos_isr_stub_0 .. moos_isr_stub_47, moos_isr_stub_128 */

/* Entry from every stub: record vector, count it, warn on unexpected CPU
 * exceptions (no panic - interrupts stay masked during bring-up), then run
 * any handler registered for this vector (cf. MOOS Interrupts.HandleInterrupt). */
void moos_intr_handler(uint64_t vec, struct moos_regs *frame);

/* Registry (cf. MOOS Interrupts.cs delegate list): fixed 256-slot table,
 * register overwrites the previous entry, fn = NULL clears it. */
void       moos_irq_register(int vec, moos_irq_fn fn);
void       moos_irq_dispatch(int vec, struct moos_regs *frame);
moos_irq_fn moos_irq_get(int vec);          /* NULL when empty / out of range */

/* stats for self test / diagnostics */
uint64_t moos_intr_last_vector(void);
uint32_t moos_intr_count(int vec);          /* 0 when out of range */
void     moos_intr_reset_stats(void);

/* boot-time self test (st_run("moos_intr", ...)) */
void st_moos_intr_test(void);

#endif /* STITCH_INTR_H */
